### ISSUE TITLE
select new groups?

### ISSUE THREAD

**Issue by gracezheng** [hackseq/2016_project_7#41] opened 2016-10-24 19:03 UTC
@esmason Is "Select new groups" working in the most current version? It does not seem to work for me (after I create groups, I cannot select new groups).

**Comment by esmason** [comment] 2016-10-24 20:18
@gracezheng do you mean after you create a new group (for instance "B cells") , then click "select new groups", the new B cell group disappears?

If so, this was never working because the create new groups feature was added after "select new groups". Select new group reloads the page which resets the state to default (ie original groups only)

this specific problem can be fixed by a different implementation of "select new groups" that does not reload the page.

more generally, this is an issue with saving state between page reloads, which is a feature that should definitely be implemented. Possiblities for this are:
- callbacks and sessions (somehow). http://shiny.rstudio.com/reference/shiny/latest/session.html
- HTTP requests that contain state (though I feel like this is a bad idea)
-  user profiles (possibly labour intensive)

**Comment by gracezheng** [comment] 2016-10-24 20:35
@esmason No, for some reason, "create a new group" does not work for me when I run the app from my laptop. However, it does work from the web (using the link from @oganm. 

I agree that we probably want to keep the annotated groups even when we want to "select new groups". The 1st possibility you listed may work. Let's circle back on that.

**Comment by esmason** [comment] 2016-10-24 21:20
Ah ok now I know what the problem is. I'll fix it later

**Comment by esmason** [comment] 2016-10-24 21:21
(It's to do with the fact that I implemented that feature with a POST request)

**Closed as completed** 2019-08-23 22:58 UTC
